import mongoose from 'mongoose';

// ─── Line Item Sub-Schema ─────────────────────────────────────────────────────
// Stored as a snapshot at time of sale so reprints stay accurate
// even if the product is later edited or deleted.
const billItemSchema = new mongoose.Schema(
  {
    productId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Product',
    },
    name: {
      type: String,
      required: true,
    },
    unitPrice: {
      type: Number,
      required: true,
    },
    quantity: {
      type: Number,
      required: true,
    },
    lineTotal: {
      type: Number,
      required: true,
    },
  },
  { _id: false } // line items don't need independent IDs
);

// ─── Bill Schema ──────────────────────────────────────────────────────────────
const billSchema = new mongoose.Schema({
  billNumber: {
    type: String,
    required: true,
    unique: true,
    // Format: TXN-YYYY-XXXX — generated by billController before saving
  },
  cashier: {
    type: String,
    required: true,
  },
  items: [billItemSchema],
  subtotal: {
    type: Number,
    required: true,
  },
  tax: {
    type: Number,
    default: 0,
  },
  discount: {
    type: Number,
    default: 0,
  },
  grandTotal: {
    type: Number,
    required: true,
  },
  paymentMethod: {
    type: String,
    enum: ['Cash', 'Card'],
    required: true,
  },
  tenderedAmount: {
    type: Number,
  },
  changeDue: {
    type: Number,
    default: 0,
  },
  createdAt: {
    type: Date,
    default: Date.now,
  },
});

const Bill = mongoose.model('Bill', billSchema);

export default Bill;
